# Generated by Django 5.2.4 on 2026-01-22 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('pk', models.CompositePrimaryKey('survey', 'recipient', blank=True, editable=False, primary_key=True, serialize=False)),
                ('survey', models.CharField(max_length=24)),
                ('recipient', models.ForeignKey(db_column='recipient', on_delete=django.db.models.deletion.CASCADE, related_name='invites_recipient_set', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('sender', models.ForeignKey(blank=True, db_column='sender', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'invites',
                'unique_together': {('sender', 'recipient')},
            },
        ),
    ]
